ingestion:
  taxa_to_fetch:
    - 47120  # Apis mellifera (Honey bees)
    - 47119  # Bombus (Bumble bees)
    - 47114  # Vespidae (Yellowjackets & Hornets)
  per_page: 200 # Request 200 images per taxon at once.

training:
  epochs: 5
  extractor: "dinov3"
  batch_size: 32
